In [86]:
import numpy as np
import itertools

In [87]:
def kbits(n, k):
    result = []
    for bits in itertools.combinations(range(n), k):
        s = ['0'] * n
        for bit in bits:
            s[bit] = '1'
        result.append(''.join(s))
    return result

In [88]:
def next_lex_permutation(n: int):
    n = np.uint32(n)
    t = (n | (n - 1)) + 1
    return t | ((((t & -t) // (n & -n)) >> 1) - 1)

In [89]:
def n_bits_integers(n, N):
    """Returns a list containing all integers that are represented by a binary string of length
       N with n ones"""
    if n > N or n < 0:
        raise ValueError("Arguments (n, N) must fulfill 0 ≤ n < N")
    base_transform = (2**(np.arange(N)[::-1])).astype(np.uint64)
    if n == 0:
        return [0]
    if n == N:
        return np.sum(np.ones(N, np.uint64)*base_transform)
    min_int = np.sum(np.ones(n, np.uint64)*base_transform[N-n::])
    max_int_bin = np.zeros(N, np.uint64)
    max_int_bin[:n] = 1
    max_int = np.sum(max_int_bin*base_transform)
    basis_states_ints = [min_int]
    current = min_int
    while (current := next_lex_permutation(current)) <= max_int:
        basis_states_ints.append(current)
    return basis_states_ints

In [90]:
n_bits_integers(2, 4)

/var/folders/t9/xqv32vzn2pb091tj9_rz1_zh0000gn/T/ipykernel_13509/2500932201.py:4: RuntimeWarning: overflow encountered in scalar negative
  return t | ((((t & -t) // (n & -n)) >> 1) - 1)


[3, 5, 6, 9, 10, 12]

In [91]:
import tiheisembergs

H = tiheisembergs.tincxxz(11, 6, 0)

In [92]:
len(H.basis_states)

42

In [93]:
H.basis_states

array([411, 413, 159, 423, 427, 683, 429, 175, 303, 437, 183, 311, 187,
       315, 189, 317,  63, 207, 335, 469, 215, 343, 219, 347, 221, 349,
        95, 231, 359, 235, 363, 237, 365, 111, 243, 371, 245, 373, 119,
       249, 123, 125])

In [94]:
f"{6877619:026b}"

'00011010001111000110110011'

In [95]:
int("0"*13+"1"*13, base=2)

8191

In [96]:
8191 in H.basis_states

False

In [97]:
H.basisstr()

['|00110011011>',
 '|00110011101>',
 '|00010011111>',
 '|00110100111>',
 '|00110101011>',
 '|01010101011>',
 '|00110101101>',
 '|00010101111>',
 '|00100101111>',
 '|00110110101>',
 '|00010110111>',
 '|00100110111>',
 '|00010111011>',
 '|00100111011>',
 '|00010111101>',
 '|00100111101>',
 '|00000111111>',
 '|00011001111>',
 '|00101001111>',
 '|00111010101>',
 '|00011010111>',
 '|00101010111>',
 '|00011011011>',
 '|00101011011>',
 '|00011011101>',
 '|00101011101>',
 '|00001011111>',
 '|00011100111>',
 '|00101100111>',
 '|00011101011>',
 '|00101101011>',
 '|00011101101>',
 '|00101101101>',
 '|00001101111>',
 '|00011110011>',
 '|00101110011>',
 '|00011110101>',
 '|00101110101>',
 '|00001110111>',
 '|00011111001>',
 '|00001111011>',
 '|00001111101>']

In [108]:
import tiheisembergs

Hbasis = tiheisembergs.tincxxz(10, 5, 0)

In [109]:
ham = Hbasis.block_hamiltonian(True, -0.5)

In [110]:
evals, evecs = np.linalg.eig(ham)
print(evals)
print(evecs)

[-15.27613112-1.25937149e-32j  -9.28742334-3.91301606e-32j
  -3.85832124+4.20068275e-32j  -0.36780291+7.44942266e-33j
   8.72148679-3.69778549e-32j   8.72148679-8.90742599e-34j
   3.7896786 -1.39431735e-32j  -6.55133547+3.20993733e-33j
   6.33645607-4.93038066e-32j   6.33645607-1.24415074e-31j
  -6.55133547-2.87149912e-32j  -5.        -3.20566387e-32j
  -4.46410162-4.62223297e-33j  -4.46410162+5.89565665e-33j
  -3.27620513+9.86076136e-32j  -3.27620513-4.91292692e-32j
  -1.82842712+9.86076131e-32j  -1.82842712+3.70741514e-32j
   3.82842712+1.69531546e-32j   3.82842712+2.94855361e-32j
   2.46410162-8.63825746e-33j   2.46410162-2.58416943e-32j
   1.76959775-1.54074384e-32j   1.76959775+1.96738258e-32j
  -1.        +3.33066907e-16j  -1.        -4.44089210e-16j]
[[ 1.28110767e-01+2.69630192e-33j -2.50582384e-01-2.31111593e-32j
  -1.04466284e-01+1.34044724e-31j  1.04353958e-01-2.21867130e-31j
   2.77629212e-01+9.47919213e-21j  2.57548780e-02-2.12711923e-19j
   1.73174818e-01-1.06311333e-31j 

In [111]:
np.linalg.norm(evecs[:, 1])

0.9999999999999999

In [112]:
np.linalg.det(evecs)

(-0.7663361467620657+0.35335568537414747j)

In [113]:
np.abs(Hbasis.change_to_comp_basis(evecs[:, 1]))**2

array([0., 0., 0., ..., 0., 0., 0.])

In [114]:
np.linalg.norm(Hbasis.change_to_comp_basis(evecs[:, 0]))

1.0000000000000002

In [115]:
import scipy.sparse as sparse

evals, evecs = sparse.linalg.eigsh(ham, k=5, which="SA")
print(evals)
np.abs(Hbasis.change_to_comp_basis(evecs[:, 1]))**2

[-15.27613112  -9.28742334  -5.          -6.55133547  -6.55133547]


array([0., 0., 0., ..., 0., 0., 0.])

In [116]:
np.linalg.norm(evecs[:, 0])

0.9999999999999997